test.out: IndyDCPConnector.h IndyDCPException.h IndyDCPUtility.h IndyDCP.h main.cpp 
	g++ -std=c++11 -o test.out main.cpp IndyDCPConnector.cpp IndyDCPException.cpp  IndyDCPConnectorCommands.cpp IndyDCP.cpp
